const ZENDESK_URLS = {
  ADD_CUSTOM_TOKENS: 'https://blog.ezwallet.xyz/',
  ADD_MISSING_ACCOUNTS: 'https://blog.ezwallet.xyz/',
  BASIC_SAFETY: 'https://blog.ezwallet.xyz/',
  CUSTOMIZE_NONCE: 'https://blog.ezwallet.xyz/',
  HARDWARE_CONNECTION: 'https://blog.ezwallet.xyz/',
  IMPORT_ACCOUNTS: 'https://blog.ezwallet.xyz/',
  IMPORTED_ACCOUNTS: 'https://blog.ezwallet.xyz/',
  INFURA_BLOCKAGE: 'https://blog.ezwallet.xyz/',
  LEGACY_WEB3: 'https://blog.ezwallet.xyz/',
  NFT_TOKENS: 'https://blog.ezwallet.xyz/',
  PASSWORD_ARTICLE: 'https://blog.ezwallet.xyz/',
  SECRET_RECOVERY_PHRASE: 'https://blog.ezwallet.xyz/',
  SECRET_RECOVERY_PHRASE_USER_GUIDE: 'https://blog.ezwallet.xyz/',
  NON_CUSTODIAL_WALLET: 'https://blog.ezwallet.xyz/',
  SPEEDUP_CANCEL: 'https://blog.ezwallet.xyz/',
  TOKEN_SAFETY_PRACTICES: 'https://blog.ezwallet.xyz/',
  UNKNOWN_NETWORK: 'https://blog.ezwallet.xyz/',
  USER_GUIDE_CUSTOM_NETWORKS: 'https://blog.ezwallet.xyz/',
  USER_GUIDE_DAPPS: 'https://blog.ezwallet.xyz/',
  USER_GUIDE_GAS: 'https://blog.ezwallet.xyz/',
  VERIFY_CUSTOM_NETWORK: 'https://blog.ezwallet.xyz/',
};

export default ZENDESK_URLS;
